; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

#define MyAppName "JaguarCC"
#define MyAppVersion "v26.0.4"
#define MyAppPublisher "Oscar Soirey"
#define MyAppURL "https://oscar-soirey.github.io/JaguarCC/"
#define EscapeConstArgument(Value) StringChange(StringChange(StringChange(Value, "%", "%25"), ",", "%2c"), "}", "%7d")
#define MyAppArchitecture "windows-x64"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{28D28AE9-5095-4784-A519-C24E12330314}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={cm:NameAndVersion,{#EscapeConstArgument(MyAppName)},{#EscapeConstArgument(MyAppVersion)}}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\User\Desktop\Jaguar\JaguarCC\dist
OutputBaseFilename=jaguarcc-{#MyAppVersion}-{#MyAppArchitecture}
SetupIconFile=C:\Users\User\Desktop\Jaguar\JaguarCC\docs\assets\logo.ico
WizardImageFile=C:\Users\User\Desktop\Jaguar\JaguarCC\docs\assets\logo.bmp
WizardSmallImageFile=C:\Users\User\Desktop\Jaguar\JaguarCC\docs\assets\logo.bmp
SolidCompression=yes
WizardStyle=modern dark
ChangesEnvironment=yes
[Registry]
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
    ValueType: expandsz; ValueName: "Path"; \
    ValueData: "{olddata};{app}"; \
    Flags: preservestringtype
    

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\Users\User\Desktop\Jaguar\JaguarCC\jbg.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\Jaguar\JaguarCC\jbs.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\Jaguar\JaguarCC\jcc.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\Jaguar\JaguarCC\crimson.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\Jaguar\JaguarCC\jlanguage_server.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\Jaguar\JaguarCC\toolchain\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.


[Code]

procedure InitializeWizard();
begin
  WizardForm.Color := $2A3B12;
end;